# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vinniefm.com
owner: Vince Mease
email: vmease@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Blog, portfolio, bio, and resume for Vince Mease, experienced Product Manager and UX Architect.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vinniefm.com" # the base hostname & protocol for your site
twitter_username: vinniefm
github_username:  vinniefm
linkedin_username: vincemease

# Build settings
markdown: kramdown
# sass:
#   style: compressed
